name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PUBLIC_ENVIRONMENT: ${{ secrets.PUBLIC_ENVIRONMENT }}
          envkey_PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
          envkey_PUBLIC_GA_TRACKING_ID: ${{ secrets.PUBLIC_GA_TRACKING_ID }}

      - name: Build Astro
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: astro-boilerplate
          entrypoint: server/entry.mjs
          root: dist
